---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-configs
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: homelab-cluster
  path: ./apps
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age          # posé par le socle (homelab-nix : k3s/flux-sops.nix)
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
