server {
  listen 8080;
  server_tokens off;
  root /usr/share/nginx/html;

  default_type text/plain;
  charset utf-8;
  add_header X-Served-By $hostname always;

  location = /        { try_files /index.txt =404; }
  location = /healthz { return 200 "ok\n"; }
  location /          { return 404 "404\n"; }
}
