# Grafana admin login (user "admin"). Read: sops -d --extract '["stringData"]["admin-password"]' infrastructure/configs/monitoring/grafana-admin.sops.yaml
apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:tQaecw0=,iv:0iGldM6Is4VQCoRrwKlq0c01OO73Ac8YBRe9rD0ttOQ=,tag:xJOrJaW5UQJiztEmIjRdkg==,type:str]
    admin-password: ENC[AES256_GCM,data:cSIBT3HKBj8NC8QWvNaR1ziOr0+CAa7PIpku+gQy3SQ=,iv:hqi9PBH7umJzkp6xE6Js2z0Csf0S5y5parWhVp+Cdig=,tag:mo1GTiFZmB6FO44sG5jZGw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4QnBtbGk3MExNYUhFeU1Q
            SXpybnVLV1EybDZ6cFo5Rnc3cVF4dmhORHhzCm1IczRockNDdmQySmxHVlBYeTVr
            Q1dic0V2dWNPeEJxZFlRZzNFcVJqaDgKLS0tIDhkN3dxYTdxUkpwWUR6dlI3YStv
            c1ptcHUxbXRqNlVReE1xaGlPaXN1YnMKyS+YToFdTvhYqs66tUN2miHZsvLzsfQl
            MJff2/SW7PDunQQo8V1Gvy2vBbEiZDfWFoDqCCZzMl8wsGUV/oixfQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uzjc82ya0szkyht2txxjsk03csk7cpap524lz9v8gjxsaqxlaejsr3tkcc
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IGo4YVdFdyBBbTRvZXdU
            Vld0RFdjNURWLzA0bk5rNUJRNDhuL0ZYdEZ3Q0JSWGJMb2FPaApTN2JaYU14Skhw
            S0lCMVgza214YnAvNi9McEViZW05ZGNRNUd1bktNMStRCi0tLSA1ZGJEcktnQmdX
            UUhDRGQ2VTJxWDhnemM4NmtYL3ZicWN4Vml5b0U1cDdzCkACumjDl5jHxbTr0jVT
            Xu1jxSVg7KmXa8eHmCf5jKDRpDY1Rpb13oMtK7RRyFrCDMYcAwiiGBaluICAi7qE
            5tY=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q23p5ysmjm8ukvad9xefunvaq7fz06zsf72jr0vj20z2j48sjjh2jm256cs
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQZzFGZ2lGMENCTlBKQUxt
            MitMalJ6VXo0N05TZE5RTjNzbGt0bFdtZnhzCkFhNEQ4dkFUSXRFMTdlc0Q4Wm5z
            WUhWSGs2OXRocmc1ajY1b2ppTzQ2VVkKLS0tIE1oR2pENTVoTTFDYWxnemU4TS92
            NEVSOEhJa1RQajN3RVJWQlBKNkxUZjQK6R+VyppLWLvdU9W06Kl11Kf26XBIAxos
            3kTRe9W8KDnOu8sNQd8uCQwCoF3qjz+f7jT/6sZiv4ZW98pZ0o3rbQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15lxalve0wl20hk7ygx5h9khexfgsws8ucue6txvfz7dgtsvsugqskgwuyc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T13:48:37Z"
    mac: ENC[AES256_GCM,data:Lz3bH+4JohlIm1P9OVuWBgcK+n4qoJpcu21VV3So2X2jWt3LERDhNJTijzvWD/SSX/H5dXJWXiQvX3F2zPBwj+e+AforyJtPT0v3SOI2KfZAgCQFqaPnCbgfYZkH1nRZCEnhWVgxSENQT/HQBZkGCP/6QO9k2ALHAAUO/7kxrOM=,iv:g9jfWfUZivSVpL6jk1ApMA651rUjHifl3kJW60b3PaA=,tag:TyOifCeFJxXPa+qJsd0G7g==,type:str]
    version: 3.13.3
