# Token API Cloudflare pour cert-manager (DNS-01). Zone abe.lc, droit DNS Edit.
# Éditer : sops infrastructure/configs/cloudflare-api-token.sops.yaml
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:ttPcXmizs5JoWeT9I98hDqXHoj2K0NQrz12sHNN2AJ7uzUp2XO+BQtyLO0YdM999WCCmhbU=,iv:i5oEXjnsGvOj6o3qht+nHPY/n4peA3Fz5ig5GCgUkq4=,tag:ZfkhS2bydKwZjXluG3D0mQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnQ1J1aHUrUzRqUG8zcnk1
            ZWw3ckd2OGl3ZHdvdFpjSFpqWG1jZERsU21ZCitxN3pxSGNvbzJKRTNGWXZxTUtr
            WlJ5L2ZiYStnRVZ3T0xuYzNJNTFQeEUKLS0tIFVsdHo2WFVaQnFWOWdabU1CdGdo
            SWIyVGI1VTJ6eEU0UnVMb3pXUlJiU3cK/7au4nRfolf3DfmOFDdHR4qQoaeXeMJm
            74C6ZsZmuHaLwY6d+2wDPt/LhT0m9hnfn2Axb2Z5/EanjcDCW3fPag==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uzjc82ya0szkyht2txxjsk03csk7cpap524lz9v8gjxsaqxlaejsr3tkcc
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IGo4YVdFdyBBcGZzSHdG
            MGRCRGdKMWFFdndqUkh5U3gzL1RWMVZzSEpkMkdTM09FOFQ4NApZdjJQUFJaZk1w
            Qll2aGhjaGZBbkRUcHhLU3NaY0pLQnd5U25iNFl6U0VBCi0tLSAvYXJybHVRWXpJ
            R2ViTE5RQko3TytZamZ3dzExcVJLbVl5WUpFTzRiYS9NCvJIK392wWeoxAHDZxUs
            yuDxp2xl8ZMaXxXV/0OyUYr3fTkrsaCP9g/bXQXY+HUHUhjDIbPr69d0ToU+Lqor
            OfM=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q23p5ysmjm8ukvad9xefunvaq7fz06zsf72jr0vj20z2j48sjjh2jm256cs
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsSWNWOXVzLzQxY2FhOEhk
            M0UyUHFobGNsa1o2UXBhNm5hb3FXQm52bmdJCjJETEJFYTVZZjlJMG5UNEIrVC9Z
            djkyRXdKTUd4aXB4Q2FVUlZ0eWl5TE0KLS0tIFVlMk1Rb3hkL016cEM2RFZCeXUv
            VWcvRzFVVFhEY3Z2UitZMllYVWYrcXcKmHJIEiYVyr7KkwEqMMEc01CYMfsggw5f
            R38DMxBWxAPlQ25ehQa/Vni+l6aUQg8DJ2zTUcZJdgSeHTxHMYBMyQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15lxalve0wl20hk7ygx5h9khexfgsws8ucue6txvfz7dgtsvsugqskgwuyc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-07T23:49:42Z"
    mac: ENC[AES256_GCM,data:ZhcFcV7Lu0jWSpdMEnUCbrcn/dT+bXatWDLnBS+4p2vO3ha38s45dNcjLGhNBmKAu+B1xPsDmzFgs8/dkj9pTqtBjgYH9NDMpaQSH6jLAraugNT+NVyF3WfFApNu1rld3FYuQNyjtmenz4UTG63yETkctbaaK3QgIzyZt/qzmGQ=,iv:f8vL9Bcf0bMQnc+gSs/FonEZaX3e/MxqUCX9+3o/C7A=,tag:f7DZcPOg0CZp4Tmh+g/aNQ==,type:str]
    version: 3.13.3
