# Token API Cloudflare pour cert-manager (DNS-01). Zone abe.lc, droit DNS Edit.
# Éditer : sops infrastructure/configs/cloudflare-api-token.sops.yaml
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:ttPcXmizs5JoWeT9I98hDqXHoj2K0NQrz12sHNN2AJ7uzUp2XO+BQtyLO0YdM999WCCmhbU=,iv:i5oEXjnsGvOj6o3qht+nHPY/n4peA3Fz5ig5GCgUkq4=,tag:ZfkhS2bydKwZjXluG3D0mQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxdmJWQ2pVYkoySlJ3VG5T
            WFUrOVVnM1VyRUM2cVZXWXRqTGcxaHhBWGpZCmdrZ3Z5ME04cDhTSGRORXk1NUcy
            dEhlV2ljeFJ5d0dzVEJIeXBPNnE4R3cKLS0tIHFjenZTZ0Y1MThXT3E5N1JYQ3hX
            RkxjUytmY0hqMGhFb3hUb1RlaFUxeWMKIMDcSo9ZYQIRHUo8wULWS+aOyubi4YFA
            Jd/Gopdwcc+UApsebSRAkQ3tCmKFvYr4aCIG//XIFJmaHoJXYmNHDg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uzjc82ya0szkyht2txxjsk03csk7cpap524lz9v8gjxsaqxlaejsr3tkcc
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IGo4YVdFdyBBOGlxckc1
            b0ptNzBFNE9LWmt0ajMxbjUyQzN2VmpJSG8wN3VyWVZZZ0RpUgpGcG9uZ1pWYkxq
            K01xaWVQTjNYSXRwS0EyMDkzalhlWDhyY0RXaE9oTXhBCi0tLSBLTmFUbEpLOVkv
            b0ZxQ0Z1MUdGWlVTMFBqOXhicmpyRlE3M2pPTjVwTkRBCrpGwPITYnQUiCgjc2WL
            6lWUxImAnyyQ4/m4Q97CHKnfeCAaqUj32gHVCpc+EDHzD+pj2Mr5UWazRnZV9PLa
            rTs=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q23p5ysmjm8ukvad9xefunvaq7fz06zsf72jr0vj20z2j48sjjh2jm256cs
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRV3FWS3NJSWgxZmFoOVp0
            cW9uRU1OeGk5RGdISmNjREFzUkpNSFkycFdrCk1peEFLWnNGVTlsSCs3dnI2b1R0
            ZEVxdXhXQklRNE9UMmpwNGFtRXI1bncKLS0tIFJabUFybitZK1BHVTh1NVR1QkVk
            anVKclpkZUZma2I5MHY3d0pGdXN2VUUKclozEsQuTQiCsJ7NHyJKKI4QlRyVmnSq
            Gr3IkBS4okzVloxVRYSTDnsSfu/SbSAvS6HSDF4zzN17qMruALHuQw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vheyl8p09efd0080vhar893dud22hktq4wst0uhd66x96xng6pqqr8rdep
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-07T23:49:42Z"
    mac: ENC[AES256_GCM,data:ZhcFcV7Lu0jWSpdMEnUCbrcn/dT+bXatWDLnBS+4p2vO3ha38s45dNcjLGhNBmKAu+B1xPsDmzFgs8/dkj9pTqtBjgYH9NDMpaQSH6jLAraugNT+NVyF3WfFApNu1rld3FYuQNyjtmenz4UTG63yETkctbaaK3QgIzyZt/qzmGQ=,iv:f8vL9Bcf0bMQnc+gSs/FonEZaX3e/MxqUCX9+3o/C7A=,tag:f7DZcPOg0CZp4Tmh+g/aNQ==,type:str]
    version: 3.13.3
