# Clé d'API Datadog (site US1) pour l'agent du cluster.
# Éditer : sops infrastructure/configs/datadog-secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
    name: datadog-secret
    namespace: datadog
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:FJE8Q1rP33PGl9xk3QXJYq+p3k533fNVBn646NqZAZQ=,iv:ED1JKyPV/mOV9rHI0+O35i6lqi2V3bz+pf4pfK3S4pQ=,tag:d+NzIwik/3hcdFToVDHq8Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzQ0lsRXlJMG42UlpsakNS
            dE1iRXI0OHF1M09sczlvamF1cWJ0bEhyazNvCjlxNEZsZHk2aUhtYTYyemVNejYw
            dU1YOHZ4d2VGdEc1TlVLK25LZ212ZEEKLS0tIEY2QnNFV3ZLYjQ3RVd4U1VHQjU5
            NVYvbWZjVDJXcVlPZFpTLzRrbGpraTQKSS6EfdL6DMBKg6g4Erg6WstcRg6x7n0r
            /fgFsp+3M1TlO9xG+dnw5tTT9Ls2iIDgqGE2ShtbWrAmQuTscLcZmg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uzjc82ya0szkyht2txxjsk03csk7cpap524lz9v8gjxsaqxlaejsr3tkcc
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IGo4YVdFdyBBL0pPT2pL
            U2Y0b21qZ25FRXZYTWUxZTdJZ2NPTURaeWgyVjFEY2hrWWVUeAplbjlnL0UxUGZ6
            b0VJbUw1RzJ6czQ4ZGdGVXZMZXZrb3dGZEdRY2JkV1o4Ci0tLSBlaUFDQzc0cDRt
            cEc4Z3h3cS9xUWoxN3FKRC9CQjlvUTltN2tOVXpXLzBBCnAew9WSQvmwrNCqUHVG
            6C48Fm2v1ZexVtiQxAREK9hROSErtDJuOl6jeyofvcMZA/KRbpMDncfaxG9x1ExQ
            LfE=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q23p5ysmjm8ukvad9xefunvaq7fz06zsf72jr0vj20z2j48sjjh2jm256cs
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5dFdvREJwYjRUYW03NUFG
            VEE2VEltZ2NmRlIvVFJsQlpVQU0zSlBVZHhvClUrWGZRakw1NDZnU1F3MEIwUkF6
            cXJhcHhMYWdUUXdTS3VQa2Ntajk5ZnMKLS0tIENWM3R0WDJNSExydGphNnNPVmdC
            ZUsrMSthV3RvMElwUDBGRytxSnhTUDAKqN/hQEhEoE3atppzZkih/at/Yn/r/fOm
            rLcz08ddkaep5SYvYgIVNGbFExkRFuQyeOPwz3Br1QV0eBZZb/IpVQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vheyl8p09efd0080vhar893dud22hktq4wst0uhd66x96xng6pqqr8rdep
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-07T23:47:47Z"
    mac: ENC[AES256_GCM,data:o9do2k7AebsyG7XYj6JwgOJeGpOVUJrtzxdAbiKTcJCnR5/Zokh3ha3kroJC8GFaaz5Z/UnwbtTK2Pb7e+o1mvM5PoXyNZtdrRSx5LaH//8yDj5RjFt0xzaLyIqa2YQ0vAsOrbCg6pnpfWMxVI0RTO7z3t9JHTM89r+6oR1qpLY=,iv:ChpywSjjE0ACk+0urVn72q0kFDBdw6KC86KbDX4XFJ4=,tag:rq0mU2a4kPDWqkmxSKivmQ==,type:str]
    version: 3.13.3
