# Clé d'API Datadog (site US1) pour l'agent du cluster.
# Éditer : sops infrastructure/configs/datadog-secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
    name: datadog-secret
    namespace: datadog
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:FJE8Q1rP33PGl9xk3QXJYq+p3k533fNVBn646NqZAZQ=,iv:ED1JKyPV/mOV9rHI0+O35i6lqi2V3bz+pf4pfK3S4pQ=,tag:d+NzIwik/3hcdFToVDHq8Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqakx6Yk5PdTBFNGQzaTY0
            eFZrOURoT2JUeVhpZCtkT0tFNHNyN1QyclNNCi9hc1c3UjZzblBMOXVyNlQwbERY
            WmtrK1V1ZWR1WTdIL2FxL0ZTb0lIQ1EKLS0tIEYyalhxZDBaRnJKUVFlM1hMMW1s
            TkhLZDlFWkgweGMza0lTOThiTEhnQW8KpyYjc6RE0p7Fej41wLr+g/Ib4xgZYcCk
            x6f7QCkj04uk2rNrqYap7WADjA1TIwItoIVW3GDOcAn2Pae6i1Aw0w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1s6hy57p80hu633xwvq2408hnh7djhh8chp7jen90uqpyymjg0upqrcg6y4
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqb0VjVlhWdFdtakw1bWVI
            WU5xYlN4cDZBWnAwVlVXTm42bURYb2Z3Y2xFCkVlRmxEU1VpN0hKd0JzTzlGQkk4
            dFd5WEFDK3JQQjBnQVdYM2ZSNnFiOWcKLS0tIExzanRhcVY1TWl4cW95Z09jU1Bq
            czlLdmtvMm5RYWVuYzZOYzhiLzRXbXcK7sW2GX9KFHAZtLyW+wSZRQ81dst3mtg3
            9VNSUhQMBBGJ+Jnegr1A4hzUBCYm7JM3gGgzLCBMx+Kjiy7Egcbl+Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vheyl8p09efd0080vhar893dud22hktq4wst0uhd66x96xng6pqqr8rdep
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-07T23:47:47Z"
    mac: ENC[AES256_GCM,data:o9do2k7AebsyG7XYj6JwgOJeGpOVUJrtzxdAbiKTcJCnR5/Zokh3ha3kroJC8GFaaz5Z/UnwbtTK2Pb7e+o1mvM5PoXyNZtdrRSx5LaH//8yDj5RjFt0xzaLyIqa2YQ0vAsOrbCg6pnpfWMxVI0RTO7z3t9JHTM89r+6oR1qpLY=,iv:ChpywSjjE0ACk+0urVn72q0kFDBdw6KC86KbDX4XFJ4=,tag:rq0mU2a4kPDWqkmxSKivmQ==,type:str]
    version: 3.13.3
