# Clé d'API Datadog (site US1) pour l'agent du cluster.
# Éditer : sops infrastructure/configs/datadog-secret.sops.yaml
apiVersion: v1
kind: Secret
metadata:
    name: datadog-secret
    namespace: datadog
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:FJE8Q1rP33PGl9xk3QXJYq+p3k533fNVBn646NqZAZQ=,iv:ED1JKyPV/mOV9rHI0+O35i6lqi2V3bz+pf4pfK3S4pQ=,tag:d+NzIwik/3hcdFToVDHq8Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoVnJSTXppTzJ5anA1eWlI
            dCtjYW56NHkwQVBNKzh5OUdLZktIUzVmeEc4CmY5MTlNNllaMTZRb0pMbGYxa1JE
            TXVtZE9SSHFSTVlTbG9hVit0NU9TVjgKLS0tIEcydzlDUjJNY1pYcEZ4aWZvWUR0
            WmxjWVpqbnlzYlhhK3hXV01vamw0aFUKvoLSvUH/4IMLZxvx1231TmqbHM0i90MO
            ZFzJnmAWg9qqfn7wp63ULD8AI9Za6V4BY1rR0XWHMfTlshw9rzN2aQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uzjc82ya0szkyht2txxjsk03csk7cpap524lz9v8gjxsaqxlaejsr3tkcc
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IGo4YVdFdyBBODBWVVNQ
            VGZIYkpnY3FKV00zQ2xKditsb3JuUldmMnJMOHE4UENTTkJBOApNOWZNa2dQTVBQ
            OU5PUEszdVZhYituVDB1NXBkeTVqTHU5cXJ6elRScHNjCi0tLSBxeWZvblNoRm5p
            SUhMZE9iaXRkS1RUVVZEYVRBMFI2TThUdFFlcm5iY2pFCvdiTh5lbXR8bfFBloIr
            kdDvVQiwEH4wEjEo4K9p7Tf5oV1Cmc9i0ojcZIS6w8pNN5ufRR2YP8yIsiV1MgWk
            kUQ=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q23p5ysmjm8ukvad9xefunvaq7fz06zsf72jr0vj20z2j48sjjh2jm256cs
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoMURnVVA5MVlaYkc4NENW
            ank0NjhUY0RtUmJZb0IyRkxoTFE1ZmY5aEI0Cm1paVFjL2piTGY0WmlDQkVES2s2
            K0pGWHplU0JNYXpCTnZWcmk5d1lYaHcKLS0tIFRXblIzVXEzWnFTeFpLRStsUkdp
            TmpPaDNLWEw5OVV0ZEFZbUtESmpjMHcK75c0ASSwtMdiRAI4Vk87CwiEuQp8jzVH
            v3ZdgcTSNlC6M770AJZCphlYuuIQRvJY9uFkbg/0F4wJ0YNKfTYqWA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15lxalve0wl20hk7ygx5h9khexfgsws8ucue6txvfz7dgtsvsugqskgwuyc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-07T23:47:47Z"
    mac: ENC[AES256_GCM,data:o9do2k7AebsyG7XYj6JwgOJeGpOVUJrtzxdAbiKTcJCnR5/Zokh3ha3kroJC8GFaaz5Z/UnwbtTK2Pb7e+o1mvM5PoXyNZtdrRSx5LaH//8yDj5RjFt0xzaLyIqa2YQ0vAsOrbCg6pnpfWMxVI0RTO7z3t9JHTM89r+6oR1qpLY=,iv:ChpywSjjE0ACk+0urVn72q0kFDBdw6KC86KbDX4XFJ4=,tag:rq0mU2a4kPDWqkmxSKivmQ==,type:str]
    version: 3.13.3
