apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - metallb-pool.yaml
  - traefik.yaml
  - security-headers.yaml
  - gateway.yaml
  - cloudflare-api-token.sops.yaml
  - cluster-issuers.yaml
  - certificate.yaml
  - datadog-secret.sops.yaml
  - datadog-agent.yaml
  - flux-datadog.sops.yaml
  - flux-datadog.yaml
