apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - metallb-pool.yaml
  - storage.yaml
  - monitoring
  - openbao
  - traefik.yaml
  - security-headers.yaml
  - gateway.yaml
  - cloudflare-api-token.sops.yaml
  - cluster-issuers.yaml
  - certificate.yaml
