# Password of the OpenBao "admin" user (UI and CLI, userpass), until Pocket-ID (OIDC).
# Read: sops -d --extract '["stringData"]["password"]' infrastructure/configs/openbao/admin-password.sops.yaml
apiVersion: v1
kind: Secret
metadata:
    name: openbao-admin-password
    namespace: openbao
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:r7dYVpjql+MoREwPZ1raPUMPKWDnWudEnhROPFunbQ==,iv:9+thv3GgyZfGIP6NGPHIikFDU5YUSqljy9bWzrypcnE=,tag:glSP9WSYZme5GFsxpbuoig==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0eE9MZHd4emxUK3JZSHVY
            RCt1bUNFRDVkdHZYZ2ZkalEzOUl0cmRYMDJJCnErV0lUbkhZL2NYdnMyTTY4RkRH
            ajJBRHhKQko2ZW5DR2x6L1dTc3A5WmMKLS0tIG5yZ2lOV2NjdlBzZGFxM0x5Y3Mr
            Q1daVTFDa0RnL25ZdEMvUkVhYTViZk0KYB28PN6bKp/U/2eH6LwMg0HIt/WeChr5
            ayACNjNe3bHC0bF5B4Gp0+z3LKgLWtwk7PcLVHMZCSYGtcEU5bVVvQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uzjc82ya0szkyht2txxjsk03csk7cpap524lz9v8gjxsaqxlaejsr3tkcc
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IGo4YVdFdyBBZ2FMUkxB
            blhzYmlNUVRsL2tVcDBLNktBNFltZkQ1RjRnS0ZHRDFLQmJ2RQpETTJrSCtISFlD
            ZUdFVHpvUGkzZnhmaDRTdldpcStxRkxiQXJQeGR2eTNrCi0tLSBjY3hEWDR1V1Zw
            MDdmKzNSWEU1WG5ZbmFDb2pScE54cFNrZmVSZHlUUjdJChtCMCpHmor6Eg07IalJ
            u5nkXIXgPCKXPYZ5L8Zwnqmtqir/sj2CMM5P9o8V6JL09T9iNrwY/O0PmX/zow2q
            JpA=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q23p5ysmjm8ukvad9xefunvaq7fz06zsf72jr0vj20z2j48sjjh2jm256cs
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSkdOWFBDVVVBa25Yd3Y1
            cVdIN2dsR09LMkdIZmNreEE5T0ZYK1Iwcmg0CnpMOFRaWmcwbDRtazB5YTc0MTFE
            Ni8zdy9rNWJyckJndVlDam9yVG0ybUkKLS0tIGR4V09OYjdVVnVtMU9DVldyWHNW
            MGxRd0NObU1oK3FJSWd1b0o5RUcyZ3MKl56NYzcOh/DkQeun5TBRv+bzlYRMJvyq
            rvHT9DOJNjTVny4bWHrG2pdYAXnWzezRZdi/RB6wLcwljjdY36+k/w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age15lxalve0wl20hk7ygx5h9khexfgsws8ucue6txvfz7dgtsvsugqskgwuyc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T14:46:52Z"
    mac: ENC[AES256_GCM,data:p9EYaITf84/jQIPfq3N11qwFeRTfH4eg4QtlewcbSzJ73zdIfQx1Yf099jy7DAe4k3xlU7EXXF6oqpJkVzTOTdBc8JTlM7fdNW/cfx33epo5mhNMVWwxgUYZjZV36QE9WwoNW52IoU3Sc5FQoDNgoEkbeDi6SHv/ewIIPp9U9H8=,iv:4AxrI1iIJEBagfPyLM57WAFT3Iu+8yMCYEIRe7dcUB4=,tag:VWbD8Xb4fsbTeNVl1vL/dA==,type:str]
    version: 3.13.3
