apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - network-policy.yaml
  - openbao.yaml
  - unseal.sops.yaml
  - config.yaml
  - postgres-openbao.sops.yaml
  - database.yaml
  - oidc.yaml
